export const STATES = [
    { 'stateKey': 'AP', 'stateValue': 'Andhra Pradesh' },
    { 'stateKey': 'AR', 'stateValue': 'Arunachal Pradesh' },
    { 'stateKey': 'AS', 'stateValue': 'Assam' },
    { 'stateKey': 'BR', 'stateValue': 'Bihar' },
    { 'stateKey': 'CH', 'stateValue': 'Chhattisgarh' },
    { 'stateKey': 'GA', 'stateValue': 'Goa' },
    { 'stateKey': 'GJ', 'stateValue': 'Gujarat' },
    { 'stateKey': 'HR', 'stateValue': 'Haryana' },
    { 'stateKey': 'HP', 'stateValue': 'Himachal Pradesh' },
    { 'stateKey': 'JK', 'stateValue': 'Jammu and Kashmir' },
    { 'stateKey': 'JH', 'stateValue': 'Jharkhand' },
    { 'stateKey': 'KA', 'stateValue': 'Karnataka' },
    { 'stateKey': 'KL', 'stateValue': 'Kerala' },
    { 'stateKey': 'MP', 'stateValue': 'Madhya Pradesh' },
    { 'stateKey': 'MH', 'stateValue': 'Maharashtra' },
    { 'stateKey': 'MN', 'stateValue': 'Manipur' },
    { 'stateKey': 'ML', 'stateValue': 'Meghalaya' },
    { 'stateKey': 'MZ', 'stateValue': 'Mizoram' },
    { 'stateKey': 'NL', 'stateValue': 'Nagaland' },
    { 'stateKey': 'OD', 'stateValue': 'Odisha' },
    { 'stateKey': 'PB', 'stateValue': 'Punjab' },
    { 'stateKey': 'RJ', 'stateValue': 'Rajasthan' },
    { 'stateKey': 'SK', 'stateValue': 'Sikkim' },
    { 'stateKey': 'TN', 'stateValue': 'Tamil Nadu' },
    { 'stateKey': 'TS', 'stateValue': 'Telangana' },
    { 'stateKey': 'TR', 'stateValue': 'Tripura' },
    { 'stateKey': 'UP', 'stateValue': 'Uttar Pradesh' },
    { 'stateKey': 'UK', 'stateValue': 'Uttarakhand' },
    { 'stateKey': 'WB', 'stateValue': 'West Bengal' }
]